### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by thezoggy** [pillone/usntssearch#149]
looking through the code I see numerous coding mistakes / spelling mistakes / cosmetic issues.. is this project dead or am i wasting my time on even worrying about it?

https://github.com/pillone/usntssearch/blob/0.48/NZBmegasearch/SearchModules/ac_NZBcc.py#L59

**Comment by G1zm0** [comment]
I hope the project is not dead, It is a nice project, but I see less respons from the developer.

**Comment by bamdaschmu** [comment]
I think, sadly, its dead.

But maybe somebody (or you thezoggy) could branch it and continue developement (Sadly I don't know s*** about python, so I'm out). There are still things to resolve like you pointed out and issues like the need for parsing a category when sending to nzbget or sab (wink).

pls somebody branch and continue this!

**Comment by thezoggy** [comment]
I did fork this and Started to look through the code... There is plenty of stuff that needs some TLC. Fork I used has plenty of 'fixes' not in the official version...  

-----Original Message-----

**Comment by Mirabis** [comment]
I planned to continue this, but time is a limiting factor :(

**Comment by siuside** [comment]
For anyone following this, to update to v51 using Mirabis/thezoggy's forks

[flask-blahblah.rhcloud.com usntssearch]\> pwd
/var/lib/openshift/xxxxxxxxxxxxxxxxxx000001/app-root/repo/wsgi/usntssearch

[flask-blahblah.rhcloud.com usntssearch]\> git remote -v
origin	https://github.com/pillone/usntssearch.git (fetch)
origin	https://github.com/pillone/usntssearch.git (push)

[flask-blahblah.rhcloud.com usntssearch]\> git remote set-url origin https://github.com/thezoggy/usntssearch.git

[flask-blahblah.rhcloud.com usntssearch]\> git remote -v
origin	https://github.com/thezoggy/usntssearch.git (fetch)
origin	https://github.com/thezoggy/usntssearch.git (push)

[flask-blahblah.rhcloud.com usntssearch]\> cd NZBmegasearch/openshift/

[flask-blahblah.rhcloud.com usntssearch]\> ./install_openshift.sh 

[flask-blahblah.rhcloud.com usntssearch]\> ctl_app retstart


That should do the trick.

**Comment by siuside** [comment]
Does NZBGet integration work for anyone? I do not see Send to NZBGet icon in the search results. I have tried it in Chromium as well as Firefox. NZBGet integration works fine for me in some of the well known underground indexes directly but I'd rather have it in NZBMegaSearch

**Comment by Mirabis** [comment]
It's not working for me either, even the API of nzbmegasearch is flaky for me

**Comment by thezoggy** [comment]
@siuside my repo had only local mods, pushed some out.. first thing was just cleaning up some code / validate pulls to make sure stuff was still working..

**Comment by siuside** [comment]
No worries. Your repo is forked from Mirabis/usntssearch, so it captures all his updates and yours. I noticed Mirabis mentioning earlier in this Issue that he hasn't got the time, so I cloned yours. We really need more devs taking this fantastic project over.

**Comment by Mirabis** [comment]
Due to some recent changes in my projects, i'm looking into fixing stuff around the project. At first wanted to remake it ... but after 2 hours i was like... it's not that bad, can just continue xD

**Comment by Mirabis** [comment]
Fixed most stuff @https://github.com/Mirabis/usntssearch/commit/44e843619a40c83c295a16ad384a9c6ab352e76e

**Comment by siuside** [comment]
@Mirabis 

That is a massive update ! Thanks.. Hopefully you are posting in r/usenet to spread the workd :)

**Comment by Mirabis** [comment]
@siuside hehe first wanted to recreate it in my own way - but ended up just editing it and hoping one day he might pick it up again :)

Havn't made a reddit post.... maybe next week

**Comment by G1zm0** [comment]
I made a package for Synology users using [Synnocommunity](https://github.com/SynoCommunity/spksrc).
The package requires Python from [Synnocommunity](https://github.com/SynoCommunity/spksrc) (of course) .

The package can be found in [this link](https://db.tt/CCp0z0j9)

Disclaimer: This is my first try making a package. I just changed the link tot the git repo. It worked on a test-synology I use with DSM5.2

**Comment by Mirabis** [comment]
mmm still hit or miss with the warp ... 404 .. gotta look into that - any of u experienced it as well?

**Comment by tifoji** [comment]
Not seeing any 404s whatsoever when I search. Maybe I can try to duplicate if you share with us exactly what you do to trigger the error.

**Comment by Mirabis** [comment]
@siuside 404 seems to be resolved when not using a reverse proxy ;S Behind a reverse proxy it feeds nzbdrone/couchpotato the urls but the urls are wrong ; (

**Comment by punkhop** [comment]
@siuside Tried running your commands to go to v51 and I get this.

[flask-peet.rhcloud.com 5357fb925973ca9d650007b0]\> pwd
/var/lib/openshift/5357fb925973ca9d650007b0
[flask-peet.rhcloud.com 5357fb925973ca9d650007b0]\> git remote -v
fatal: Not a git repository (or any parent up to mount point /var/lib/openshift)

What am I doing wrong?

**Comment by punkhop** [comment]
So which repo should I install from, @Mirabis or @thezoggy ? I just created a new OpenShift gear and (successfully, I think) installed from thezoggy, but I get a 404 error after the install.

**Comment by thezoggy** [comment]
Use mirabis

-----Original Message-----

**Comment by tifoji** [comment]
@punkhop 

You do not need new gear. I got a notification from your original query but looks like you might have deleted it, but I thought I'd post here for everyone's benefit. To update to Mirabis fork, run the following commands and you should be able to update to v53.

The pwd is here just for demo to show which subdirectory one needs to be in order to run the commands (all the way upto /var/lib/openshift/xxxxxxxxxxxxxxxxxx000001/app-root/repo/wsgi/usntssearch)

[flask-blahblah.rhcloud.com usntssearch]> pwd
/var/lib/openshift/xxxxxxxxxxxxxxxxxx000001/app-root/repo/wsgi/usntssearch

[flask-blahblah.rhcloud.com usntssearch]> git remote -v
origin https://github.com/pillone/usntssearch.git (fetch)
origin https://github.com/pillone/usntssearch.git (push)

[flask-blahblah.rhcloud.com usntssearch]> git remote set-url origin https://github.com/Mirabis/usntssearch.git

[flask-blahblah.rhcloud.com usntssearch]> git remote -v
origin https://github.com/Mirabis/usntssearch.git (fetch)
origin https://github.com/Mirabis/usntssearch.git (push)

[flask-blahblah.rhcloud.com usntssearch]> cd NZBmegasearch/openshift/

[flask-blahblah.rhcloud.com usntssearch]> ./install_openshift.sh

[flask-blahblah.rhcloud.com usntssearch]> ctl_app retstart

**Comment by punkhop** [comment]
Switched to @Mirabis's repo and got it up and running - but my log is full of errors:

http://mega-peet.rhcloud.com/log

**Comment by Mirabis** [comment]
Looks like u toggled 'Https' and ur config file is missing the 'general' section ;o  Does ur install have a custom_params.ini file?

**Comment by punkhop** [comment]
Uhhhh, it shouldn't. I didn't mess with anything after the install.

**Comment by Mirabis** [comment]
Hmm - does it work though? If -so u can ignore the errors for now. 
Will check if I get the same later.

Ur reverse proxy is set to : http://gyazo.com/64388a3737301f71d71d2b3b03effc85  -> remove that ( did it for u xD)

PS: Your site does not ask for username/password, I could access ur /config freely :-1:

**Comment by punkhop** [comment]
Yeah, I did that on purpose for now so you could check it out hassle-free. I'll see if it works. I was running all my usenet apps on my hackintosh but moved them to my Synology and I can't get them working right with permissions. Once I get em right then I can test. If I ever do.
