### ISSUE TITLE
Empty NZB file when added to Sabnzbd from NZBmegasearch

### ISSUE THREAD

**Issue by seanvree** [pillone/usntssearch#169]
Setup on my Windows 10 Ent box:

NZBmegasearch http://127.0.0.1:5000 
SABNZBd: http://127.0.0.1:38080 

if I do a manual search in NZBmegasearch and send it to my SANZBD interface, it picks it up instantly, but then comes back with this error:

---
## Empty NZB file Kaskade%20Automatic%202015%20C4%20DeoTester%2013%20kaskade%20where%20are%20you%20now%20feat%20tamra%20keenan.nzb.nzb [http://192.168.1.20:5000/ http://member.nzbclub.com/nzb_get/82335 ... keenan.nzb ]

it's not the NZB file, because I download the same .nzb file from the same link and drop it in the watched folder and it downloads fine. 

I just set up NZBmegasearch, so I'm pretty new to this. 

What am I doing wrong?

**Comment by albino1** [comment]
Just so you know, this project is abandoned.  You should try NZB Hydra as a replacement instead:

https://github.com/theotherp/nzbhydra
